name: Release
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=5m
          install-mode: "goinstall"
      - name: Test
        run: go test ./...
  release-please:
    name: Run Release Please
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Release Please
        uses: google-github-actions/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.CR_PAT }}
          release-type: simple
          changelog-path: CHANGELOG.md
          package-name: rsl
